### ISSUE TITLE
SCoordinator name appears wrong in SID: Woods1 insteads of Pamela Woods.

### ISSUE THREAD

**Issue by martinezinigo** [ices-tools-prod/icesSD#40]
after i introduced her on the SID as ACoord with her mail, Woods1 appears on the drop menu insteads of Pamela Woods. i dont not if this is my mistake or a system glich.

cheers,
Inigo

**Comment by mikeydrew** [comment]
In order to add a new Stock Coordinator, they need to be firstly added to the Stock Coordinator role in RCT. Then they need to be added to SID, through the Users Module in the management section. These steps have been followed and she now appears in the list.
