### ISSUE TITLE
approving feedback

### ISSUE THREAD

**Issue by RuthFG** [ices-tools-prod/icesSD#42]
Hi Mike. 
It seems that even when feedback for the 2018 data call is approved by stock coordinators, this is not registered in the report we can download from here:
http://reporting/reports/report/Data%20Calls/Published%20Info

Can we fix that?
We do get the information on whether the Data call was approved or not.

Thanks

Ruth

**Comment by mikeydrew** [comment]
Problem resolved, Ruth was referring to Assessment Year 2019 in the report and not 2018.
