### ISSUE TITLE
1 more option  in the Advice type drop down list

### ISSUE THREAD

**Issue by JetteFredslund** [ices-tools-prod/icesSD#47]
I am currently trying to update info on stocks  in SID with info in the AA. For that, I need one more option in the drop down list for Advice type. It will be used for the stocks that the EU requests "No advice, only advice on stock status relative to MSY and PA". A more catchy label would be "stock status".

**Comment by RuthFG** [comment]
I think "stock status only" may be a better label since we try to give stock status advice for all the stocks (i.e. also for the ones for which we have catch advice).

**Comment by JetteFredslund** [comment]
Yes, I think that's a better idea.

**Comment by JetteFredslund** [comment]
Oh damn - Mike, I meant "Advice category" not "advice type" - sorry

**Comment by mikeydrew** [comment]
Hi Jette, you can update the vocabs in the manage module ->

![image](https://user-images.githubusercontent.com/10516840/40484005-53cd33d0-5f5a-11e8-8259-6256dc0a3655.png)
