### ISSUE TITLE
correction of stock name

### ISSUE THREAD

**Issue by RuthFG** [ices-tools-prod/icesSD#54]
Hello,

spr.27.3a and spr.27.4 do no longer exists since now we have a combined stock; spr.27.3a4. In the data call module (year=2019) we still have spr.27.3a and spr.27.4 and it should be corrected.
Should this not have been automatically updated from vocabularies?

Cheers

**Comment by RuthFG** [comment]
what is needed is a correction in the stock code, not the stock name!

**Comment by RuthFG** [comment]
OK, the merging of the 2 stocks in one has not been registered in SID yet... that is the problem I guess

**Comment by Osanna123** [comment]
Hi Ruth, the new stock is created in RECO and SID, but it seems that there was some kind of error with two old stock codes. i will disable them for 2019 in the vocab

**Comment by mikeydrew** [comment]
spr.27.3a is deleted for 2019 data call and the data call records for spr.27.4 for 2019 have been updated to spr.27.3a4.
