### ISSUE TITLE
ank.27.78ab to be changed to ank.27.78abd

### ISSUE THREAD

**Issue by RuthFG** [ices-tools-prod/icesSD#56]
Hello,
a stock code needs correction.
ank.27.78ab to be changed to ank.27.78abd

cheers

**Comment by mikeydrew** [comment]
Hi Ruth, It has already been updated for active years 2018 and 2019 
![image](https://user-images.githubusercontent.com/10516840/55537768-3d5fb180-56bd-11e9-9af6-a3cb78c372a5.png)

Also, it has already been updated for Assessment years 2019 and 2020 in the DataCalls
![image](https://user-images.githubusercontent.com/10516840/55537923-87489780-56bd-11e9-9480-efea1eccbfeb.png)
