### ISSUE TITLE
downloading Tables rounded too much

### ISSUE THREAD

**Issue by RuthFG** [ices-tools-prod/icesSD#57]
Hi,
When downloading the word doc. out of SAG for this stock
https://standardgraphs.ices.dk/manage/ViewGraphsAndTables.aspx?key=10416

The catches figures get rounded too much. For example in 2018 it should be 1644 tonnes of landings but in the .doc we get 1640 tonnes

Cheers

**Comment by mikeydrew** [comment]
Hi Ruth, this is an issue with SAG and not SID, therefore closing. Please run this past Carlos.
