### ISSUE TITLE
Confirmed Benchmark Meeting

### ISSUE THREAD

**Issue by slarge** [ices-tools-prod/icesSD#6]
Create a "Confirmed Benchmark Meeting" drop-down to assign each stock to a benchmark process. Each benchmark process will be from the RCT and fields such as benchmark date, and benchmark chair should be made available in "internal ICES" web service output

**Comment by mikeydrew** [comment]
I have added the new meeting type 'Benchmark' to the RCT. Any meetings that have this type will be made available to SID, so that they can be selected in relevant records.

**Comment by slarge** [comment]
Hi Mike - thanks for the work on the enhancement. On the drop down, options include "WKNSEA 2017 - Data evaluation", which isn't really useful. I imagine this is coming from RCT? I'll converse with Michala about it and see if we need you to filter these out, as they might be confusing.

**Comment by mikeydrew** [comment]
Hi Scott, I have updated the procedure to ignore any benchmark meetings with '- Data evaluation' in the text and removed those that were already imported. FYI the import / synch job runs once per day at 23:33.

**Comment by slarge** [comment]
Hi Mike - Could you help me understand why some processes are appearing in the drop-down 2x? Perhaps "WKPELA - Data evaluation" and "WKPELA" are both being listed? Thanks for your thoughts on this.

![image](https://user-images.githubusercontent.com/5000131/32775440-ba0c42f6-c92f-11e7-8705-9dcbec5f4a5e.png)

**Comment by mikeydrew** [comment]
![wkpela](https://user-images.githubusercontent.com/10516840/32781571-d13586ca-c945-11e7-92fc-0fa015ba739d.PNG)
Hi Scott, this is because there are two Benchmarks with the same name added for 2017.
