### ISSUE TITLE
stock code label - all lowercase

### ISSUE THREAD

**Issue by slarge** [ices-tools-prod/icesSD#7]
A few StockKeyLabels are displaying as sentence case (e.g., pil.27.7 and pil.27.8abd) on http://sd.ices.dk/. Anna O checked ICES vocab and the were all lower case, so there must be a bug somewhere making these Pil.xyz

**Comment by Osanna123** [comment]
just a fast comment: there is no bug responsible for making the codes with upper case. They were created this way in the vocab by Carlos. But after editing in the vocabulary, the codes did not get updated in the stock list, as expected

**Comment by mikeydrew** [comment]
Have made the changes as requested. The reason that there was no automatic update after changing to lower case is that the synch procedure does not check for differences in case.
