### ISSUE TITLE
Rename data category x.yz -> x.y.z

### ISSUE THREAD

**Issue by colinpmillar** [ices-tools-prod/icesSD#8]
An example is:
2.11 -> 2.1.1
http://sd.ices.dk/services/datacategory/2.11/2017

Jette has more info!

**Comment by mikeydrew** [comment]
This can be done by using the web gui :- http://sd.ices.dk/Manage/vocabs.aspx and selecting the ICES data category vocab.

**Comment by colinpmillar** [comment]
Thanks mike ☺  Will let Jette know
